version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1496332897
layout:
  /header/:
    -
      - system-messages-6378
    -
      - 'logo-8595 56'
      - 'iconmenu-4051 44'
  /navigation/:
    -
      - 'menu-4821 80'
      - 'social-9913 20'
  /showcase/: {  }
  /container-9505/:
    -
      -
        'mainbar 67':
          -
            - system-content-5601
      -
        'sidebar 33': {  }
  /extension/: {  }
  /footer/:
    -
      - 'custom-8436 33.3333'
      - 'newsletter-3610 33.3333'
      - 'custom-4714 33.3334'
  /copyright/:
    -
      - copyright-4509
  offcanvas:
    -
      - mobile-menu-5533
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      class: box1
      boxed: ''
  mainbar:
    type: section
  sidebar:
    type: section
  container-9505:
    title: Main
    attributes:
      id: g-main
      boxed: ''
  extension:
    type: section
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  copyright:
    type: section
    attributes:
      boxed: ''
content:
  system-messages-6378:
    layout: false
  logo-8595:
    layout: false
    block:
      class: g-logo-block
  iconmenu-4051:
    title: 'Icon Menu'
    layout: false
    block:
      class: flush
  menu-4821:
    layout: false
    block:
      class: g-menu-block
  social-9913:
    layout: false
  system-content-5601:
    layout: false
    block:
      class: nomarginall
      variations: box2
  custom-8436:
    title: 'About Aphrodite'
    attributes:
      html: "<h2 class=\"g-title\">About Aphrodite</h2>\n\n<p>All demo content is for sample purposes only, intended to represent a live site.</p>\n\n<p>The sample pages are intended to show how Aphrodite can be constructed on your site.</p>"
    layout: false
  newsletter-3610:
    attributes:
      title: Newsletter
      headtext: 'Subscribe to our newsletter and stay updated on the latest developments and special offers!'
      inputboxtext: 'Email Address'
      buttontext: Join
      uri: rocketthemeblog
      buttonclass: 'button button-3'
    layout: false
  custom-4714:
    title: 'Sample Sitemap'
    attributes:
      html: "<h2 class=\"g-title\">Sample Sitemap</h2>\n\n<div class=\"g-grid\">\n\t<div class=\"g-block\">\n\t\t<ul class=\"nomarginall noliststyle\">\n\t\t\t<li><a href=\"#\">Home</a></li>\n\t\t\t<li><a href=\"#\">Features</a></li>\n\t\t\t<li><a href=\"#\">Typography</a></li>\n\t\t\t<li><a href=\"#\">Particles</a></li>\n\t\t\t<li><a href=\"#\">Variations</a></li>\n\t\t</ul>\t\t\n\t</div>\n\t<div class=\"g-block\">\n\t\t<ul class=\"nomarginall noliststyle\">\n\t\t\t<li><a href=\"#\">Buttons</a></li>\n\t\t\t<li><a href=\"#\">Pages</a></li>\n\t\t\t<li><a href=\"#\">Guide</a></li>\n\t\t\t<li><a href=\"#\">Support</a></li>\n\t\t\t<li><a href=\"#\">Download</a></li>\n\t\t</ul>\t\t\n\t</div>\t\n</div>"
    layout: false
  copyright-4509:
    attributes:
      date:
        start: '2007'
      owner: 'RocketTheme, LLC'
    layout: false
    block:
      class: center
  mobile-menu-5533:
    title: 'Mobile Menu'
    layout: false
